name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Check code formatting with Spotless
      run: mvn spotless:check


    - name: Build and Test with Maven
      run: mvn clean verify

    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=writetojags
          -Dsonar.projectKey=writetojags_tolerant-reader-service
          -Dsonar.java.binaries=target/classes
          -Dsonar.branch.name=main
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions@v1
      with:
        args: test --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

